spring:
  application:
    name: ingredient-categories-service
  config:
    import: "optional:configserver:http://localhost:8888"
    cloud:
      config:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ingredient_categories
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
