spring:
  application:
    name: ingredient-categories-service
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true