spring:
  application:
    name: ingredients-service
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true
