spring:
  cloud:
    gateway:
      routes:
        - id: ingredient-categories-service
          uri: lb://ingredient-categories-service
          predicates:
            - Path=/api/ingredient-categories/**

        - id: ingredients-service
          uri: lb://ingredients-service
          predicates:
            - Path=/api/ingredients/**

        - id: recipe-step-service
          uri: lb://recipe-step-service
          predicates:
            - Path=/api/recipe-steps/**